# docker-compose.yml (Final Version)

version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./scraper:/opt/airflow/scraper
      - ./airflow_home:/opt/airflow/airflow_home
      - ./dags:/opt/airflow/dags
      - "./database:/opt/airflow/database"
      - ./config:/opt/airflow/config
    environment:
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # Use an environment variable to signal that the user has been created
      - AIRFLOW_USER_CREATED=false
      # --- SMTP Configuration ---
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=ratnam2001shree@gmail.com
      - AIRFLOW__SMTP__SMTP_PASSWORD=hpks ryjb tjbs tvbo
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=airflow-scraper@yourdomain.com
      - AIRFLOW__SMTP__SMTP_STARTTLS=True
      - AIRFLOW__SMTP__SMTP_SSL=False

    command: >
      bash -c "
        airflow db upgrade;
        if [[ \"$AIRFLOW_USER_CREATED\" != \"true\" ]]; then
          echo 'Creating admin user...';
          airflow users create \
            --username admin \
            --password admin \
            --firstname Admin \
            --lastname User \
            --role Admin \
            --email admin@example.com && \
          export AIRFLOW_USER_CREATED=true;
        fi;
        echo 'Starting webserver and scheduler...';
        exec airflow webserver & exec airflow scheduler
      "