# config/scraper_config.yaml

target_sites:
  - company_name: Google
    base_url: "https://careers.google.com"
    search_path: "/jobs/results/"
    keywords:
      - Data Engineer Intern
      - Data Scientist Intern
    location_query: "USA" # Or adjust as needed
    selectors:
      # --- Updated Selectors based on your HTML snippet ---
      job_card: "li.lLd3Je"        # The list item containing each job
      title: "h3.QJPWVe"           # The H3 tag with the job title
      link: "a.WpHeLc"             # The anchor tag with the specific job link
      location: "span.r0wTof"
      # --- Next Page Selector ---
      next_page: "a[aria-label='Go to next page']" 
    max_pages: 2 

  # - ... other site configurations ...